version: "3.5"

services:
  app:
    build: .
    tty: true
    stdin_open: true
    user: root
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV= development
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOSTNAME}
    ports:
      - 3000:3000
      - 19000:19000
      - 19001:19001
      - 19002:19002
    command: >
      /bin/bash -c "yarn install && yarn ${PLATFORM}"
